### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by smlombardi** [angular-ui/AngularJS-Atom#37] opened 2015-05-19 00:39 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:582:9)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:184:43)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:355:14)
PackageManager.loadPackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:325:14)
```

**Comment by joshuajabbour** [comment] 2015-05-20 18:15
Duplicate of #31

**Closed** 2015-05-22 03:29 UTC
