### ISSUE TITLE
Package.loadSettings is deprecated.

### ISSUE THREAD

**Issue by mrenfinger** [angular-ui/AngularJS-Atom#35] opened 2015-05-14 18:16 UTC
Store package settings files in the `settings/` directory instead of `scoped-properties/`
```
Package.loadSettings (/Users/michaelenfinger/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:586:9)
<unknown> (/Users/michaelenfinger/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:188:43)
Package.measure (/Users/michaelenfinger/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:167:15)
Package.load (/Users/michaelenfinger/Desktop/Atom.app/Contents/Resources/app.asar/src/package.js:181:12)
```

**Comment by joshuajabbour** [comment] 2015-05-20 18:15
Duplicate of #31

**Closed** 2015-05-22 03:29 UTC
