### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by zoiodev** [angular-ui/AngularJS-Atom#38] opened 2015-05-19 22:14 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `angularjs` package
```
Package.getStylesheetsPath (/Users/rodrigocosta/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:464:9)
Package.getStylesheetPaths (/Users/rodrigocosta/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:475:32)
Package.loadStylesheets (/Users/rodrigocosta/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:457:38)
<unknown> (/Users/rodrigocosta/Downloads/Atom.app/Contents/Resources/app.asar/src/package.js:187:19)
```

**Comment by joshuajabbour** [comment] 2015-05-20 18:10
Duplicate of #34 & #36

**Closed** 2015-05-22 03:29 UTC
