### ISSUE TITLE
Package.getStylesheetsPath is deprecated.

### ISSUE THREAD

**Issue by smlombardi** [angular-ui/AngularJS-Atom#36] opened 2015-05-19 00:39 UTC
Store package style sheets in the `styles/` directory instead of `stylesheets/` in the `angularjs` package
```
Package.getStylesheetsPath (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:460:9)
Package.getStylesheetPaths (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:471:32)
Package.loadStylesheets (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:453:38)
<unknown> (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:183:19)
Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:177:12)
```

**Comment by joshuajabbour** [comment] 2015-05-20 18:10
Duplicate of #34

**Closed** 2015-05-22 03:29 UTC
